### ISSUE TITLE
Change repo name

### ISSUE THREAD

**Issue by gwaybio** [WayScience/phenotypic_profiling_model#63]
I'm suggesting to change the repository name from `phenotypic_profiling_model` to `phenotypic_profiling`. We do more than just present the "model" in this repo. What do you think @jenna-tomkinson , @roshankern, @MattsonCam

**Comment by jenna-tomkinson** [comment]
I think this is a good idea. 👍 Makes the repo name simpler and reflects the manuscript title.

**Comment by roshankern** [comment]
I agree, feel free to change!

**Comment by gwaybio** [comment]
Perfect! Let's change this after we merge all outstanding PRs but before DOI minting 👍

**Comment by gwaybio** [comment]
renamed! Closing this issue now.

The next steps are 1) to perform a final full pass through the manuscript; 2) add any additional minor modifications to this repo; 3) Mint!
